import path from "node:path";
import { Option } from "commander";
import type { AlfredCommand } from "./schema";

export const SHELLS = ["zsh", "bash", "fish"] as const;
export type Shell = (typeof SHELLS)[number];

export function isShell(value: unknown): value is Shell {
    return SHELLS.includes(value as Shell);
}

export function detectShell(env: NodeJS.ProcessEnv = process.env): Shell | undefined {
    const shell = path.basename(env.SHELL ?? "");
    return isShell(shell) ? shell : undefined;
}

/**
 * The scripts are static: they call `alfred __complete <shell> -- "<line>"`,
 * so completions always reflect the current commands file.
 */
const SCRIPTS: Record<Shell, string> = {
    zsh: `#compdef alfred
# zsh completion for alfred, generated by \`alfred completion zsh\`
_alfred() {
  local -a candidates
  local IFS=$'\\n'
  candidates=($(alfred __complete zsh -- "\${BUFFER[1,CURSOR]}" 2>/dev/null))
  if (( \${#candidates} )); then
    _describe -t alfred 'alfred' candidates
  else
    _files
  fi
}
if [ "$funcstack[1]" = "_alfred" ]; then
  _alfred "$@"
else
  compdef _alfred alfred
fi
`,
    bash: `# bash completion for alfred, generated by \`alfred completion bash\`
_alfred() {
  local IFS=$'\\n'
  local line="\${COMP_LINE:0:COMP_POINT}"
  local word="\${line##*[[:space:]]}"
  COMPREPLY=($(alfred __complete bash -- "$line" 2>/dev/null))
  # bash splits words on ":" (e.g. "git:commit"), only complete the last part
  if [[ "$word" == *:* && "$COMP_WORDBREAKS" == *:* ]]; then
    local prefix="\${word%"\${word##*:}"}"
    COMPREPLY=("\${COMPREPLY[@]#"$prefix"}")
  fi
}
complete -o default -F _alfred alfred
`,
    fish: `# fish completion for alfred, generated by \`alfred completion fish\`
complete -c alfred -f -a '(alfred __complete fish -- (commandline -cp))'
`,
};

export function completionScript(shell: Shell): string {
    return SCRIPTS[shell];
}

export interface Candidate {
    value: string;
    description?: string;
}

const GLOBAL_OPTIONS: Candidate[] = [
    { value: "--help", description: "Show help" },
    { value: "--version", description: "Show version number" },
];

/** Split the command line up to the cursor, keeping the words after "alfred". */
export function wordsFromLine(line: string): string[] {
    const words = line.trim().split(/\s+/).filter(Boolean);
    if (/\s$/.test(line) || words.length === 0) {
        words.push("");
    }
    const start = words.findLastIndex((word, index) => index < words.length - 1 && path.basename(word) === "alfred");
    return words.slice(start === -1 ? 1 : start + 1);
}

/**
 * @param words words after "alfred", the last one is the word being completed
 */
export function completionCandidates(
    words: string[],
    commands: AlfredCommand[],
    builtins: Candidate[]
): Candidate[] {
    const current = words.at(-1) ?? "";
    if (words.length <= 1) {
        if (current.startsWith("-")) {
            return GLOBAL_OPTIONS;
        }
        return [
            ...commands.map((command) => ({ value: command.name, description: command.description })),
            ...builtins,
        ];
    }

    const name = words[0];
    if (name === "completion") {
        return words.length === 2 ? SHELLS.map((shell) => ({ value: shell })) : [];
    }
    const command = commands.find((candidate) => candidate.name === name);
    if (!command) {
        return [];
    }
    const options = command.options.map((definition) => ({ definition, option: new Option(definition.flags) }));

    // Completing the value of an option
    const previous = words.at(-2) ?? "";
    const previousOption = options.find(({ option }) => previous !== "" && (option.long === previous || option.short === previous));
    if (previousOption && (previousOption.option.required || previousOption.option.optional)) {
        const values = previousOption.definition.choices ?? (previousOption.definition.type === "boolean" ? ["true", "false"] : []);
        if (values.length || previousOption.option.required) {
            return values.map((value) => ({ value }));
        }
    }

    const used = new Set(words.slice(1, -1));
    return [
        ...options
            .filter(({ option }) => !used.has(option.long ?? "") && !used.has(option.short ?? ""))
            .map(({ definition, option }) => ({
                value: option.long ?? option.short!,
                description: definition.description || definition.flags,
            })),
        { value: "--help", description: "Show help" },
    ];
}

export function formatCandidates(shell: Shell, allCandidates: Candidate[], current: string): string {
    // One candidate per line
    const candidates = allCandidates.map(({ value, description }) => ({
        value,
        description: description?.replace(/\s+/g, " ").trim(),
    }));
    switch (shell) {
        case "zsh":
            // _describe uses ":" as separator
            return candidates
                .map(({ value, description }) => value.replaceAll(":", "\\:") + (description ? `:${description}` : ""))
                .join("\n");
        case "bash":
            return candidates
                .map(({ value }) => value)
                .filter((value) => value.startsWith(current))
                .join("\n");
        case "fish":
            return candidates.map(({ value, description }) => value + (description ? `\t${description}` : "")).join("\n");
    }
}
